OBJS = wmt_comm.o  \
       wmt_msvd.o  \
       wmt_mjpeg.o   \
       wmt_mpeg2.o   \
       wmt_mpeg4.o   \
       wmt_divx.o    \
       wmt_h263.o    \
       wmt_h264.o    \
       wmt_vc1.o     \
       wmt_rv.o      \
       wmt_vpx.o     \
       wmt_h264enc.o 
#       wmt_ac3.o     
